- hosts: auth
  tasks:
  - import_role: 
      name: install.cockpit

  - name: Install 389 from Debian
    become: yes
    ansible.builtin.apt:
      update_cache: true
      install_recommends: false
      name: 
      - 389-ds-base
      - cockpit-389-ds
      state: present

