- name: Desired state configuration for 'auth'
  hosts: auth
  tasks:
    - name: Install Cockpit
      ansible.builtin.import_role:
        name: install.cockpit

    - name: Install 389 from Debian
      ansible.builtin.apt:
        update_cache: true
        install_recommends: false
        name:
          - 389-ds-base
          - cockpit-389-ds
        state: present
      become: true

    - name: Configure system for LDAP authentication
      ansible.builtin.import_role:
        name: auth.ldap

    - name: Summarize services
      ansible.builtin.import_role:
        name: service.summary

  vars:
    services:
      - name: LDAP
        desc: "Lightweight Directory Access Protocol"
        ports: 389/tcp
