proxmox_hosts:
  hosts:
    omega:
      ansible_host: 10.1.1.8
proxmox_hosted:
  children:
    proxmox_vms:
      hosts:
    proxmox_lxc:
      hosts:
        filer:
        auth:
        db:
        git:
        nextcloud:
development:
  hosts:
    alpha:
    rho:
    rho-win11:
    mu:
    pi:
    epsilon:
    winbuild01:
ungrouped:
  hosts:
    power:
tailscale:
  hosts:
    omega:
    nextcloud:
