- name: Desired state configuration for 'epsilon'
  hosts: epsilon
  tasks:
    - name: Install Java
      ansible.builtin.import_role:
        name: devtools.java
      vars:
        java_versions:
          - "21"
          - "25"
