
- name: Install SSSD from Debian
  become: yes
  ansible.builtin.apt:
    update_cache: true
    install_recommends: false
    name:
    - sssd-ldap
    - libsss-sudo
    state: present
  when: ansible_distribution == "Debian"

- name: Configure SSSD
  ansible.builtin.template:
    src: sssd_conf.j2
    dest: "/etc/sssd/conf.d/homelab.conf"
    owner: root
    group: root
    mode: "0600"

- import_role:
    name: install.homelab_ca

- name: Start SSSD
  ansible.builtin.systemd_service:
    name: sssd
    enabled: true
    state: started

