- name: Desired state configuration for QuickEmu VM 'windows-11' on 'rho'
  hosts: rho-win11
  tasks:
    - name: Install Java
      ansible.builtin.import_role:
        name: devtools.java
      vars:
        java_versions:
          - "17"
          - "21"
          - "25"
