- name: Desired state configuration for 'rho'
  hosts: rho
  tasks:
    - name: Install Java
      ansible.builtin.import_role:
        name: devtools.java
      vars:
        java_versions:
          - "17"
          - "21"
          - "25"
