Alias /nextcloud "{{ nextcloud.install_dir }}/nextcloud"

<Directory {{ nextcloud.install_dir }}/nextcloud>
  Require all granted
  AllowOverride All
  Options FollowSymLinks MultiViews

  <IfModule mod_dav.c>
    Dav off
  </IfModule>
</Directory>
