- name: Desired state configuration for 'alpha'
  hosts: alpha
  tasks:
    - name: Install Java
      ansible.builtin.import_role:
        name: devtools.java
      vars:
        java_versions:
          - "17"
          - "21"
          - "25"
