- name: Install Homelab CA certs on Debian
  ansible.builtin.copy:
    src: "{{ homelab_root }}/ca/root/certs/ca.crt.pem"
    dest: /usr/local/share/ca-certificates/homelab-ca.crt
    owner: root
    group: root
    mode: '0644'
  when: ansible_distribution == "Debian"

- name: Reconfigure 'ca-certificates' on Debian
  become: yes
  command: "/usr/sbin/update-ca-certificates"
  when: ansible_distribution == "Debian"

